protected/models/Skills.php
<?php

/**
 * This is the model class for table "cv16_skills".
 *
 * The followings are the available columns in table 'cv16_skills':
 * @property string $id
 * @property string $skill_category_id
 * @property string $name
 * @property string $created_at
 * @property string $updated_at
 *
 * The followings are the available model relations:
 * @property JobSkill[] $jobSkills
 * @property ProfileSkills[] $profileSkills
 */
class Skills extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'cv16_skills';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
			array('skill_category_id', 'length', 'max'=>10),
			array('name', 'length', 'max'=>255),
			array('created_at, updated_at', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, skill_category_id, name, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'jobSkills' => array(self::HAS_MANY, 'JobSkill', 'skill_id'),
			'profileSkills' => array(self::HAS_MANY, 'ProfileSkills', 'skill_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'skill_category_id' => 'Skill Category',
			'name' => 'Name',
			'created_at' => 'Created At',
			'updated_at' => 'Updated At',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('skill_category_id',$this->skill_category_id,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('created_at',$this->created_at,true);
		$criteria->compare('updated_at',$this->updated_at,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
       
	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Skills the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
        public function  getName(){
           $skillcmodel =  SkillCategories::model()->findByPk($this->skill_category_id);
           return ($skillcmodel == null ? "" : $skillcmodel->name);
        }
}

protected/controllers/SkillsController.php
<?php

class SkillsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
//			array('deny',  // deny all users
//				'users'=>array('*'),
//			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Skills;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Skills']))
		{
			$model->attributes=$_POST['Skills'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Skills']))
		{
			$model->attributes=$_POST['Skills'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Skills');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Skills('search');
                $skillcmodel = SkillCategories::model();
		$model->unsetAttributes();  // clear any default values
		     
                if(isset($_GET['Skills']))
                {
                    $model->attributes = $_GET['Skills'];
                }
                if(isset($_GET['SkillCategories']))
                {
                    $model->skill_category_id = $_GET['SkillCategories']['id'];
                    //echo var_dump($_GET['Employers']['id']);                die();
                    $skillcmodel->id = $model->skill_category_id;
                }
                
                 $this->render('admin',array(
                   'model'=>$model,'skillcmodel'=>$skillcmodel
               ));

	}
        
        
         /**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actioncreateSkills() {

            $model = new Skills;
            $skillcmodel = SkillCategories::model();

            $now = new DateTime();
            
            if(isset($_POST['Skills']))
            {
                $model->attributes = $_POST["Skills"];
            }
            
            if(isset($_POST['Skills']))
            {
                $valid = $model->validate();
                
                if($valid)
                {
                    $model->skill_category_id = $_POST['SkillCategories']['id'];
                    $model->created_at = $now->format('Y-m-d H:i:s');
                    if($model->save())
                    {
                        Yii::app()->user->setFlash('success', 'Successfully created.');
                        $this->redirect($this->createUrl('skills/admin'));
                    }
                }
            }

           $this->render('create',array(
                'model'=>$model,
            ));
            
        }
        
        function actionskillsEdit($id)
	{
	    $model = Skills::model()->findByPk($id);
	    $skillcmodel = SkillCategories::model()->findByPk($model->skill_category_id);
	    if($skillcmodel == null)
	        $skillcmodel = new SkillCategories();
	    $this->render('edit',array('model'=>$model,'skillcmodel'=>$skillcmodel));
	}
        
        
        function actionupdateSkills($id) {
            
            $model = Skills::model()->findByPk($id);
            $skillcmodel = SkillCategories::model();

            $now = new DateTime();

    //      insert user details
            $model->attributes = $_POST["Skills"];
            $model->skill_category_id = $_POST['SkillCategories']['id'];
            $model->created_at = $now->format('Y-m-d H:i:s');

            $model->save();
            
            $model->unsetAttributes();  // clear any default values

           $this->render('admin',array(
                   'model'=>$model,'skillcmodel'=>$skillcmodel
            ));
                  
        }
        
        /**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
        public function actiondeleteSkills()
        {
            $ids = implode(',', $_POST['ids']);
            $now = new DateTime();

            $cri = new CDbCriteria();
            $cri->condition = "id in (".$ids.")";
            Skills::model()->deleteAll($cri);

        }

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Skills the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Skills::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Skills $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='skills-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function beforeAction($action)
	{
	    Yii::app()->user->setReturnUrl(Yii::app()->request->getUrl());
	    $requestUrl=Yii::app()->request->url;
	    if (Yii::app()->user->isGuest)
	        $this->redirect(Yii::app()->createUrl('site/login'));
	        
	        return parent::beforeAction($action);
	} 
}

protected/views/skills/_form.php
<?php
/* @var $this IndustriesController */
/* @var $model Industries */
/* @var $form CActiveForm */
?>

<?php
$form = $this->beginWidget('CActiveForm', array(
    'id' => 'skills-form',
    'action' => $this->createUrl('skills/createSkills'),
    'enableAjaxValidation' => false,
    'htmlOptions' => array('enctype' => 'multipart/form-data')
        ));
?>
<?php echo  $form->errorSummary(array($model), '<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>', '', array('class' => 'alert alert-danger')); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <?php echo $form->labelEx($model, 'name'); ?>
            <?php echo $form->textField($model, 'name', array('class' => 'form-control', 'placeholder' => 'Name')); ?>
        </div>
        <div class="form-group">
            <?php
            // $empmodel = new Employers;
            $skmodel = SkillCategories::model()->findAll();
            $skclist = CHtml::listData($skmodel, 'id', 'name');
            echo $form->dropDownList(SkillCategories::model(), 'id', $skclist, array('class' => 'form-control'));
            ?>
        </div>
        <?php echo CHtml::submitButton('Save', array("class" => "btn btn-primary")); ?>
        <?php echo CHtml::button('Cancel', array("class" => 'btn btn-primary', "onClick" => "window.location='" . Yii::app()->createUrl('skills/admin', array()) . "'")); ?>

    </div>
</div>

<?php $this->endWidget(); ?>

protected/views/skills/_search.php
<?php

/* @var $this InstitutionsController */
/* @var $model Institutions */
/* @var $form CActiveForm */
?>

<?php

$form = $this->beginWidget('CActiveForm', array(
    'action' => Yii::app()->createUrl($this->route),
    'method' => 'get',
        ));
?>

<?php echo $form->textField($model, 'name', array('class' => 'form-control','placeholder'=>'Search')); ?>

<?php

// $empmodel = new Employers;
$skmodel = SkillCategories::model()->findAll();
$skclist = CHtml::listData($skmodel, 'id', 'name');
echo $form->dropDownList($skillcmodel, 'id', $skclist, array('class' => 'form-control', 'empty' => '- Filter Category -'));
?>

<?php

echo CHtml::submitButton('Search', array("class" => 'btn btn-primary'));
?>

<?php $this->endWidget(); ?>

protected/views/skills/_view.php
<?php
/* @var $this SkillsController */
/* @var $data Skills */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('skill_category_id')); ?>:</b>
	<?php echo CHtml::encode($data->skill_category_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_at')); ?>:</b>
	<?php echo CHtml::encode($data->created_at); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('updated_at')); ?>:</b>
	<?php echo CHtml::encode($data->updated_at); ?>
	<br />


</div>

protected/views/skills/admin.php
<?php
/* @var $this SkillsController */
/* @var $model Skills */

$this->breadcrumbs = array(
    'Skills' => array('index'),
    'Manage',
);

//$this->menu=array(
//	array('label'=>'List Skills', 'url'=>array('index')),
//	array('label'=>'Create Skills', 'url'=>array('create')),
//);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#skills-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<script>
    $(document).ready(function () {


        $('#delete-skills').click(function (e) {


            if ($("#skills-grid").find("input:checked").length > 0)
            {

                if (confirm('Are you sure you want to delete these skills?')) {

                    var ids = $.fn.yiiGridView.getChecked("skills-grid", "selectedIds");

                    $.ajax({
                        url: '<?php echo $this->createUrl('skills/deleteSkills') ?>',
                        type: 'POST',
                        data: {ids: ids},
                        success: function (data) {
                            location.reload();
                        },
                        error: function (data) {
                            alert('err');
                        }
                    });
                }

            } else
            {
                alert('Please select at least one item');
            }
        });

    });

</script>
<h1>Career Paths</h1>
<div class='Admin__content__inner'>
    <?php if (Yii::app()->user->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <?php echo Yii::app()->user->getFlash('success'); ?>
        </div>
    <?php endif; ?>
    <div class='AdminFilters'>
        <div class="form-inline">
            <?php
            $this->renderPartial('_search', array(
                'model' => $model, 'skillcmodel' => $skillcmodel
            ));
            ?>
        </div>
        <div class="pull-right">
            <?php
            echo CHtml::button('Create', array("class" => "btn btn-primary", "onclick" => "window.location='" . Yii::app()->createUrl('skills/create') . "'"));
            echo CHtml::button('Delete', array("class" => "btn btn-primary", 'id' => 'delete-skills'));
            ?>
        </div>
    </div>

    <?php
    $this->widget('zii.widgets.grid.CGridView', array(
        'id' => 'skills-grid',
        'itemsCssClass' => 'table',
        'summaryText' => '',
        //'cssFile'=>Yii::app()->baseUrl . '/themes/Dev/css/style.css',
    'pager' => array(
        //'cssFile' => Yii::app()->baseUrl . '/themes/Dev/css/style.css',
        'header'=>'',
        'firstPageLabel' => '<<<',
        'lastPageLabel' => '>>>',
        'nextPageLabel' => '>>',
        'prevPageLabel' => '<<'),
        'ajaxUpdate' => false,
        'dataProvider' => $model->search(),
        //'filter'=>$model,
        'columns' => array(
            //'id',
            array(
                // 'name' => 'check',
                'id' => 'selectedIds',
                'value' => '$data->id',
                'class' => 'CCheckBoxColumn',
                'selectableRows' => 2,
            // 'checked'=>'Yii::app()->user->getState($data->id)',
            // 'checkBoxHtmlOptions' => array('name' => 'idList[]'),
            ),
            array(
                'header' => 'Name',
                'value' => 'CHtml::link("<i class=\"fa fa-pencil\"></i> ".$data->name,Yii::app()->createUrl("skills/skillsEdit",array("id"=>$data->id)),array("class"=>"skills-edit-button","id"=>"skills-edit"))',
                'type' => 'raw'
            ),
            array(
                'header' => 'Industry',
                'value' => '$data->skill_category_id > 0 ? $data->getName() : ""',
                'type' => 'raw'
            ),
        ),
    ));
    ?>

</div>



protected/views/skills/create.php
<?php
/* @var $this SkillsController */
/* @var $model Skills */

$this->breadcrumbs=array(
	'Skills'=>array('index'),
	'Create',
);

//$this->menu=array(
//	array('label'=>'List Skills', 'url'=>array('index')),
//	array('label'=>'Manage Skills', 'url'=>array('admin')),
//);
?>

<h1>Create Skills</h1>
<div class="Admin__content__inner">
<?php $this->renderPartial('_form', array('model'=>$model)); ?>
</div>

protected/views/skills/edit.php
<?php
/* @var $this IndustriesController */
/* @var $model Industries */
/* @var $form CActiveForm */
?>
<h1>Edit Career Path</h1>
<div class="Admin__content__inner">
       <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'skills-form',
        'action' => $this->createUrl('skills/updateSkills',array('id'=>$model->id)),
        'enableAjaxValidation' => false,
        'htmlOptions' => array('enctype' => 'multipart/form-data')
    ));
    ?>
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <?php echo $form->labelEx($model, 'name'); ?>
                <?php echo $form->textField($model, 'name', array('class' => 'form-control', 'placeholder' => 'Name')); ?>
                <?php echo $form->error($model, 'name'); ?>
            </div>
            <div class="form-group">
                <?php 
                    // $empmodel = new Employers;
                     $skmodel = SkillCategories::model()->findAll();
                     $skclist = CHtml::listData($skmodel, 'id', 'name');
                     echo $form->dropDownList($skillcmodel,'id',$skclist,array('class'=>'form-control'));
                ?>
            </div>
            <?php echo CHtml::submitButton('Save', array("class" => "btn btn-primary")); ?>
            <?php echo CHtml::button('Cancel',array("class"=>'btn btn-primary',"onClick"=>"window.location='".Yii::app()->createUrl('skills/admin',array())."'")); ?>

        </div>
    </div>
    
    
    <?php $this->endWidget(); ?>
</div>

protected/views/skills/index.php
<?php
/* @var $this SkillsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Skills',
);

$this->menu=array(
	array('label'=>'Create Skills', 'url'=>array('create')),
	array('label'=>'Manage Skills', 'url'=>array('admin')),
);
?>

<h1>Skills</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/skills/update.php
<?php
/* @var $this SkillsController */
/* @var $model Skills */

$this->breadcrumbs=array(
	'Skills'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Skills', 'url'=>array('index')),
	array('label'=>'Create Skills', 'url'=>array('create')),
	array('label'=>'View Skills', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Skills', 'url'=>array('admin')),
);
?>

<h1>Update Skills <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/skills/view.php
<?php
/* @var $this SkillsController */
/* @var $model Skills */

$this->breadcrumbs=array(
	'Skills'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Skills', 'url'=>array('index')),
	array('label'=>'Create Skills', 'url'=>array('create')),
	array('label'=>'Update Skills', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Skills', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Skills', 'url'=>array('admin')),
);
?>

<h1>View Skills #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'skill_category_id',
		'name',
		'created_at',
		'updated_at',
	),
)); ?>